### ISSUE TITLE
Is there a way to use it in Linux

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#1]

**Comment by ghost** [comment]
Also, can you add "Chapter" section like pages? It is way useful when I add normal manga not hentai or doujin.

**Comment by nilfoer** [comment]
Should've worked on GNU/Linux already as is, but i forgot to add the **pillow** package dependency to *requirements.txt*. Sorry about that!

You can download the source zip including third-party dependencies (not the one generated by github) and run:
```
pip3 install -r requirements.txt
```
Or you can download the zip of the `_standalone-linux-x64` pre-compiled version that includes python as well as all other dependencies (I only tested this on WSL2 with Ubuntu 20.04 LTS).

If you have troubles installing **pillow** using pip, make sure you have the packages `libjpeg-dev` and `zlib1g-dev`installed  (in the package manager of your distro), since pillow needs those to build.

I also added a chapter field where you can add arbitrary text like "Vol. 2 Ch. 9". Hope that's close enough to what you wanted.

If you want more features (e.g. importing manga information from a site) just open a new issue.

**Comment by ghost** [comment]
Thank you so much!
