### ISSUE TITLE
Support getting information from MangaDex

### ISSUE THREAD

**Issue by ghost** [nilfoer/mangadb#2]
It would be so awesome, I wish you would add it when you have free time. Thanks. I have some recommendation for this program but sadly I have no knowledges about coding so cant help with it.

**Comment by nilfoer** [comment]
I added an extractor for MangaDex, which is included in the [new release](https://github.com/nilfoer/mangadb/releases/tag/v0.21.0). 

Since we don't have a chapter system the solution is a little hacky and some fields that don't apply are hidden. But other than not being able to add chapters and a disabled 'Read Online' button you shouldn't notice anything of that while you're using it.

**Comment by ghost** [comment]
Thank you so much!
