### ISSUE TITLE
Be able to set permanent sort.

### ISSUE THREAD

**Issue by ruchisa-dev** [nilfoer/mangadb#3]
I want to Sort as Ascending with English titles but I want them to be permanent. Also showing number of how much manga you read and you are reading currently would be nice.

**Comment by nilfoer** [comment]
The webGUI now remembers your sorting preferences until the session cookie runs out. That's not permanent, but the session cookie stays valid for 10 days then you have to log-in again anyway.

I couldn't really think of a good place to display the reading information, instead I made it so you can search for books that you've read, are currently reading or are still unread. Let me know if that works for you.

**Comment by ruchisa-dev** [comment]
When I did click to any manga my preferences were gone, I am using standalone windows version with instance folder that comes default.

Searching reading status is really good, it works thanks.

**Comment by ruchisa-dev** [comment]
Now, there are no bug like that but can we left it as open I would like to let you know if that happens again.

**Comment by ghost** [comment]
I have figured it out, If you do Ascending with English id therefore click any manga and search something search bar while manga's detail page, it becomes same as default settings.

**Comment by ghost** [comment]
About count of status you could add them left of where my cursor is but just the count of searched status. If you would think that Reading=50 would seem bad you could just write 50 with small fonts.
![image](https://user-images.githubusercontent.com/43301560/105860848-13e4e800-5fff-11eb-8d13-0f204730547e.png)

**Comment by omgitsmoe** [comment]
It only remebers your sorting preferences if you perform a new search or refresh the current one (using the 'Refresh search button').

I experimented with adding counts of read books etc. or just the number of books matching the current query, but I didn't like how it looked. So I'd rather keep it how it works currently. (From the programming side, showing the number of matched items for a search query is very inefficient as well, since the DB has to traverse all the search results.)

Showing number of matched books:
![grafik](https://user-images.githubusercontent.com/60219950/105896889-b5783380-6017-11eb-9f27-c5764a984c91.png)

Showing reading status:
![grafik](https://user-images.githubusercontent.com/60219950/105896936-c759d680-6017-11eb-8c6d-94f756e27b10.png)

**Comment by nilfoer** [comment]
It only saves your sorting preferences when you perform a new search or refresh the current one (using the 'Refresh search' button).

I experimented with adding the count of read books etc. or just the number of matched books for the current search query, but I didn't like how it looked. I'd rather keep the current solution of searching for the `read_status`. (From the programming side, displaying a total number of matched items for a given query is also very inefficient, since the DB has to iterate over all the resulting rows.)

Showing number of matched books:
![grafik](https://user-images.githubusercontent.com/60221153/105897823-f755a980-6018-11eb-80a7-dcfd84cf5646.png)


Showing reading status:
![grafik](https://user-images.githubusercontent.com/60221153/105897832-fa509a00-6018-11eb-94f1-548f820be36c.png)

**Comment by ghost** [comment]
If you say so, it is okay. Thanks for your hardworking.

**Comment by ruchisa-dev** [comment]
Oh okay then. Thanks for everything!
